# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: add.proto for package 'proto'

require 'grpc'
require 'add'

module Proto
  module Test

    # TODO: add proto service documentation here
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'proto.Test'

      rpc :Add, NumericRequest, NumericResponse
    end

    Stub = Service.rpc_stub_class
  end
end
